import { Inter } from "next/font/google";
import "../globals.css";
import '../fontawesom.js'; 
import UserContext from '@/app/component/context/UserContext'
import Navbar from "../component/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
